version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qhus60fl8gq
      POSTGRES_DB: bd_gym
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Inyección automática de tablas (Asegúrate de que la ruta a bd.sql sea correcta)
      - ./backend/bd.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: qhus60fl8gq
      DB_NAME: bd_gym
      JWT_SECRET: super-secreto-gymtrack-clave-dificil-de-adivinar-123
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
